### ISSUE TITLE
Create React App Template Not Working

### ISSUE THREAD

**Issue by waream2** [stoplightio/cra-template-elements-dev-portal#2]
## Describe the bug

I'm running `npx create-react-app my-dir --template @stoplight/elements-dev-portal` and getting the following error back `error An unexpected error occurred: "https://registry.yarnpkg.com/@stoplight%2fcra-template-elements-dev-portal: Not found".`

## To Reproduce

1. Run this CLI command `npx create-react-app my-dir --template @stoplight/elements-dev-portal`
2. See error `error An unexpected error occurred: "https://registry.yarnpkg.com/@stoplight%2fcra-template-elements-dev-portal: Not found".`

## Expected behavior

I expect a React app to be created with the elements-dev-portal template.

## Additional context
N.a

**Screenshots**
N.a

**Environment (remove any that are not applicable):**
 - OS: [11.4]
 - Platform: [CLI in Visual Studio Code]

**Comment by mpodlasin** [comment]
Hey, could you provide me with your node and npm versions?

**Comment by waream2** [comment]
Sure, thank you for the response.

Node: v14.17.0
npm: 6.14.13

**Comment by mpodlasin** [comment]
Ah, sorry. By accident we made the package private, so it worked only for us. 😅 

Please confirm that you can install now and I'll close the issue.

**Comment by waream2** [comment]
It worked, thank you.

**Comment by mpodlasin** [comment]
Thanks for reporting! 🎉
